name: Build and Push Docker Image

description: Builds and pushes the Docker image to the GitHub Container Registry.

inputs:
  version:
    description: "The version to tag the image with"
    required: true
  github_token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ inputs.version }}
    
    - name: Cleanup
      if: ${{ failure() || cancelled() }}
      uses: actions/github-script@v8
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const tagName = 'v${{ inputs.version }}';
          const releases = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          const release = releases.data.find(release => release.tag_name === tagName);
          if (release) {
            await github.rest.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id
            });
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/${tagName}`
            });
            console.log('Docker build failed, release and tag deleted!');
          }
